name: Build and Quality Check

on: [push, pull_request]

env:
  SOLUTION_PATH: EasySave_Project/EasySave_Project.sln
  DOTNET_VERSION: '8.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_PATH }}
        continue-on-error: true  # Permet de continuer même si cette étape échoue

      - name: Build project
        run: dotnet build ${{ env.SOLUTION_PATH }} --no-restore --configuration Release
        continue-on-error: true  # Continue en cas d'erreur de build

      - name: Run tests
        run: dotnet test ${{ env.SOLUTION_PATH }} --no-restore --configuration Release
        continue-on-error: true  # Continue même si les tests échouent

  commit_message_validation:
    runs-on: ubuntu-latest
    name: Commit Message Validation
    steps:
      - uses: actions/checkout@v3

      - id: verify_commit_message
        uses: uptownaravi/verify-commit-message-action@v2
        with:
          regex: '^(hotfix|release|feature|main|develop)\[.+\] : .+'
        continue-on-error: true  # Continue même si la validation échoue

  notify-discord:
    needs: [build, commit_message_validation]  # Exécuter après les jobs build et validation du message
    if: always()  # Exécute toujours, même en cas d'échec des jobs précédents
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{
                  "username": "CI/CD Pipeline",
                  "avatar_url": "https://cdn-icons-png.flaticon.com/512/5968/5968322.png",
                  "embeds": [{
                    "title": "🚨 La pipeline a échoué !",
                    "description": "Une erreur s'est produite lors de l'exécution de la pipeline sur la branche `${{ github.ref_name }}`.",
                    "color": 16711680,
                    "fields": [
                      {
                        "name": "Nom du Workflow",
                        "value": "${{ github.workflow }}"
                      },
                      {
                        "name": "Lien vers les logs",
                        "value": "[Voir les détails](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
                      }
                    ]
                  }]
                }' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}