name: Build and Quality Check

on: [push, pull_request]

env:
  SOLUTION_PATH: EasySave_Project/EasySave_Project.sln
  DOTNET_VERSION: '8.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build project
        run: dotnet build ${{ env.SOLUTION_PATH }} --no-restore --configuration Release

      - name: Run tests
        run: dotnet test ${{ env.SOLUTION_PATH }} --no-restore --configuration Release

      # - name: SonarCloud Scan
      #   uses: sonarsource/sonarcloud-github-action@master
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   with:
      #     args: >
      #       -Dsonar.projectKey=ton-projet
      #       -Dsonar.organization=ton-organisation
      #       -Dsonar.host.url=https://sonarcloud.io

  
  commit_message_validation:
    runs-on: ubuntu-latest
    name: Commit Message Validation
    steps:
      - uses: actions/checkout@v3
      - id: verify_commit_message
        uses: uptownaravi/verify-commit-message-action@v2
        with:
          regex: '^(hotfix|release|feature|main|develop)\[.+\] : .+'

  notify-discord:
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{
                  "username": "CI/CD Pipeline",
                  "avatar_url": "https://cdn-icons-png.flaticon.com/512/5968/5968322.png",
                  "embeds": [{
                    "title": "🚨 La pipeline a échoué !",
                    "description": "Une erreur s'est produite lors de l'exécution de la pipeline sur la branche `${{ github.ref_name }}`.",
                    "color": 16711680,
                    "fields": [
                      {
                        "name": "Nom du Workflow",
                        "value": "${{ github.workflow }}"
                      },
                      {
                        "name": "Job échoué",
                        "value": "${{ github.job }}"
                      },
                      {
                        "name": "Erreur",
                        "value": "Vérifiez les logs dans l'action GitHub."
                      },
                      {
                        "name": "Lien vers les logs",
                        "value": "[Voir les détails](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
                      }
                    ]
                  }]
                }' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
